name: Auto Deploy Backend to Oracle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy to Oracle Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH naar Oracle en draai deploy.sh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: bash ~/deploy.sh
